version: "3.1"

services:
  template-build:
    container_name: goRest-build
    image: maven:3.8.5-amazoncorretto-17
    command: sh -c "cd back && mvn clean package"
    volumes:
      - ./:/back

  template-service:
    container_name: goRest-service
    domainname: goRest-service
    hostname: goRest-service
    ports:
      - "8080:8080"
    build:
      context: .
    environment:
      APP_URL: http://localhost:8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sf_tuts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - "db"
    links:
      - "db:db"

  db:
    container_name: sf_tuts
    ports:
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sf_tuts
